#!/bin/bash

SCRIPTNAME="remove"

##############################################################################
# common script header (adapt log file name)
# The script has to be run as root
#if [[ $EUID -ne 0 ]]; then
#   echo "This script must be run as root!"
#   echo "Issue a 'sudo bash' before running it."
#   exit 1
#fi

# grab current directory
currDir=$(pwd)

## set up logging
## first store existing output redirects
## use "exec 1>$STDOUT 2>$STDERR" whenever you want to restore 
#STDOUT=`readlink -f /proc/$$/fd/1`
#STDERR=`readlink -f /proc/$$/fd/2`
#exec > "$currDir/$SCRIPTNAME".log 2>&1
#exec < /dev/null
#set -x

##############################################################################

# read configuration file
#source ./build_vm.cfg
#source ./ancillary.conf
source ./lacp-vm.conf

#vmName="msr2400-demo"

remove_vm()
{
  virsh destroy $vmName
  virsh undefine $vmName
}

###### Main
remove_vm
#echo "VM Name: $vmName"
